import type { ModelEntry } from '@/types/misc'

/** Static demonstration registry (spec 10.6). */
export const MODEL_REGISTRY: ModelEntry[] = [
  {
    id: 'ike-parser-rules',
    name: 'ike-parser-rules',
    task: 'IKE/ESP header and proposal parsing',
    version: '1.4.0',
    type: 'Rule-based',
    macroF1: 1.0,
    lastTrained: '2026-08-30',
    latencyMs: 0.4,
    params: '214 parsing rules',
  },
  {
    id: 'cipher-fingerprint-gbm',
    name: 'cipher-fingerprint-gbm',
    task: 'ESP cipher and integrity family',
    version: '2.1.3',
    type: 'GBM',
    macroF1: 0.962,
    lastTrained: '2026-09-12',
    latencyMs: 3.1,
    params: '512 trees x depth 12',
  },
  {
    id: 'mode-pfs-replay-gbm',
    name: 'mode-pfs-replay-gbm',
    task: 'Tunnel/transport, PFS, replay, ESN',
    version: '1.8.0',
    type: 'GBM',
    macroF1: 0.934,
    lastTrained: '2026-09-12',
    latencyMs: 2.7,
    params: '384 trees x depth 10',
  },
  {
    id: 'traffic-cnn1d',
    name: 'traffic-cnn1d',
    task: 'Traffic type inside ESP',
    version: '3.0.2',
    type: 'CNN',
    macroF1: 0.887,
    lastTrained: '2026-09-18',
    latencyMs: 11.8,
    params: '420 k parameters',
  },
  {
    id: 'traffic-transformer',
    name: 'traffic-transformer',
    task: 'Traffic type (ensemble member)',
    version: '0.9.1',
    type: 'Transformer',
    macroF1: 0.901,
    lastTrained: '2026-09-21',
    latencyMs: 24.6,
    params: '1.8 M parameters',
  },
]
