#!/usr/bin/env python
"""Generate all M1 config artifacts from testbed/matrix.py.

Outputs (all derived, never hand-edited):
  testbed/variants/<id>/gw-{a,b}/swanctl.conf     primary strongSwan configs
  testbed/configs/<id>/gw-{a,b}/ipsec.conf        legacy configs (fallback)
  testbed/configs/<id>/gw-{a,b}/ipsec.secrets     legacy PSK file
  testbed/labels/variants.json                    per-variant ground truth

Usage:
  .venv/bin/python testbed/gen_configs.py
  .venv/bin/python testbed/validate_configs.py   # verification gate

Config facts this generator encodes (all verified empirically against
strongSwan 5.9.1, see testbed/DESIGN.md "Empirical verification"):
  * every setting on its own line inside {} (inline comma syntax invalid);
  * `version = 2` / `version = 1` (the token `ikev2` is rejected);
  * `pfs` is a no-op -> PFS is expressed as a DH token in esp_/ah_proposals;
  * child proposal key is esp_proposals / ah_proposals (never `proposals`);
  * `id-1`/`id-2` are valid only inside secrets{}, auth blocks use `id =`;
  * transport mode requires host TS owned by the IKE endpoints (subnet TS
    is rejected with TS_UNACCEPTABLE) -> transport variants use /32, /128
    transit-link addresses as selectors;
  * conn-level `encap = yes` forces NAT-T ESP-in-UDP (legacy: forceencaps).
"""
from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import matrix as m  # noqa: E402

TESTBED = Path(__file__).resolve().parent
VARIANTS_DIR = TESTBED / "variants"
CONFIGS_DIR = TESTBED / "configs"
LABELS_DIR = TESTBED / "labels"

GENERATED_BANNER = "generated by testbed/gen_configs.py - DO NOT EDIT, regenerate instead"


def _comment(v: dict) -> str:
    ike = m.ike_proposal(v)
    prop_key, child = m.child_proposal_key(v), m.child_proposal(v)
    return (
        f"# {GENERATED_BANNER}\n"
        f"# variant {v['id']}: {v['description']}\n"
        f"# ike_proposal={ike} child_proposal={child} ({prop_key})\n"
    )


def swanctl_conf(v: dict, gw: str) -> str:
    """One swanctl config file (connections + secrets sections)."""
    local, remote = m.endpoints(v, gw)
    local_ts, remote_ts = m.traffic_selectors(v, gw)
    my_id, peer_id = gw, ("gw-b" if gw == "gw-a" else "gw-a")
    child = m.child_name(v)
    conn = m.conn_name(v)
    esp_key = m.child_proposal_key(v)
    child_prop = m.child_proposal(v)

    lines = [_comment(v)]
    lines.append("connections {")
    lines.append(f"  {conn} {{")
    lines.append(f"    version = {v['ike_version']}")
    lines.append(f"    local_addrs = {local}")
    lines.append(f"    remote_addrs = {remote}")
    lines.append(f"    proposals = {m.ike_proposal(v)}")
    lines.append(f"    rekey_time = {v['ike_rekey_s']}")
    if v["nat_t"]:
        lines.append("    encap = yes")
    lines.append("    local {")
    lines.append("      auth = psk")
    lines.append(f"      id = \"{my_id}\"")
    lines.append("    }")
    lines.append("    remote {")
    lines.append("      auth = psk")
    lines.append(f"      id = \"{peer_id}\"")
    lines.append("    }")
    lines.append("    children {")
    lines.append(f"      {child} {{")
    lines.append(f"        local_ts = {local_ts}")
    lines.append(f"        remote_ts = {remote_ts}")
    lines.append(f"        mode = {v['mode']}")
    lines.append(f"        {esp_key} = {child_prop}")
    lines.append(f"        rekey_time = {v['child_rekey_s']}")
    lines.append(f"        replay_window = {v['replay_window']}")
    lines.append("      }")
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    lines.append("secrets {")
    lines.append(f"  ike-{conn} {{")
    lines.append("    id-1 = \"gw-a\"")
    lines.append("    id-2 = \"gw-b\"")
    lines.append(f"    secret = \"{m.psk_for(v['id'])}\"")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def legacy_ipsec_conf(v: dict, gw: str) -> str:
    """Legacy ipsec.conf (starter format) for the same variant."""
    local, remote = m.endpoints(v, gw)
    local_ts, remote_ts = m.traffic_selectors(v, gw)
    my_id, peer_id = gw, ("gw-b" if gw == "gw-a" else "gw-a")
    is_transport = v["mode"] == "transport"

    lines = [_comment(v)]
    lines.append("# ipsec.conf - strongSwan IPsec configuration file")
    lines.append("config setup")
    lines.append("")
    lines.append(f"conn {m.conn_name(v)}")
    lines.append(f"    type={v['mode']}")
    lines.append(f"    keyexchange=ikev{v['ike_version']}")
    if v["ike_version"] == 1:
        lines.append("    aggressive=no")
    lines.append(f"    ike={m.ike_proposal(v)}")
    if v["ipsec_protocol"] == "ah":
        lines.append(f"    ah={m.child_proposal(v)}")
    else:
        lines.append(f"    esp={m.child_proposal(v)}")
    lines.append(f"    left={local}")
    lines.append(f"    right={remote}")
    lines.append(f"    leftid={my_id}")
    lines.append(f"    rightid={peer_id}")
    if not is_transport:
        lines.append(f"    leftsubnet={local_ts}")
        lines.append(f"    rightsubnet={remote_ts}")
    lines.append(f"    ikelifetime={m.legacy_lifetime(v, 'ike')}")
    lines.append(f"    keylife={m.legacy_lifetime(v, 'child')}")
    lines.append(f"    replay_window={v['replay_window']}")
    if v["nat_t"]:
        lines.append("    forceencaps=yes")
    lines.append("")
    return "\n".join(lines) + "\n"


def legacy_secrets(v: dict) -> str:
    return (
        f"# {GENERATED_BANNER}\n"
        f"gw-a gw-b : PSK \"{m.psk_for(v['id'])}\"\n"
    )


def _clean_generated_dirs() -> None:
    """Remove previously generated v<N> trees (nothing else)."""
    for base in (VARIANTS_DIR, CONFIGS_DIR):
        if not base.exists():
            continue
        for child in base.iterdir():
            if child.is_dir() and re.fullmatch(r"v\d+", child.name):
                shutil.rmtree(child)


def write_labels() -> None:
    LABELS_DIR.mkdir(parents=True, exist_ok=True)
    rows = [m.label_row(v) for v in m.VARIANTS]
    (LABELS_DIR / "variants.json").write_text(
        json.dumps(rows, indent=2) + "\n", encoding="utf-8"
    )
    # A complete per-pcap example record (first variant + per-pcap fields),
    # validated against label_schema.json by validate_configs.py.
    example = dict(rows[0])
    example.update(
        {
            "traffic_type": "icmp",
            "source": "synthetic",
            "run_id": "r1",
            "duration_s": 10.0,
            "packet_count": 147,
        }
    )
    (LABELS_DIR / "example-label.json").write_text(
        json.dumps(example, indent=2) + "\n", encoding="utf-8"
    )


def main() -> int:
    _clean_generated_dirs()
    n_sw = n_lg = 0
    for v in m.VARIANTS:
        for gw in ("gw-a", "gw-b"):
            sw = VARIANTS_DIR / v["id"] / gw
            lg = CONFIGS_DIR / v["id"] / gw
            sw.mkdir(parents=True, exist_ok=True)
            lg.mkdir(parents=True, exist_ok=True)
            (sw / "swanctl.conf").write_text(swanctl_conf(v, gw), encoding="utf-8")
            (lg / "ipsec.conf").write_text(legacy_ipsec_conf(v, gw), encoding="utf-8")
            (lg / "ipsec.secrets").write_text(legacy_secrets(v), encoding="utf-8")
            n_sw += 1
            n_lg += 2
    write_labels()
    print(
        f"generated {n_sw} swanctl configs, {n_lg} legacy files, "
        f"labels for {len(m.VARIANTS)} variants"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
